# -*- coding: utf-8 -*-
"""corrigindo codigo bolo 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CGmtQCKQzpfnw5KSXWogSI3hOXCKBOLi
"""

#Rceita de Bolo
#ENTRADA -> PROCESSAMENTO ->SAIDA
#Problema: fazer um bolo chocolate
#IDE vscode LP Python

#Passo 1: Identificação do problema.
#Passo 2: Escolha das Ferramentas
#Passo 3: Implementação, Testes, Validações ...

###Entradas###
#Ingredientes
#uma colher de chá fermento
#3 xícaras de farinha
#3 ovos
#2 xicaras cacau em pó(chocolate)
#1 xicara leite
#1/2 xicara margarina
#uma lata chatilly
#3 xícaras açucar
#meia colher de chá de sal

###Processamento###
#seprar uma vasilha para misturar os ingredientes
#acrescentar os ingredientes na vasilha
#misturar os ingedientes na vasilha ate ficar homogeneo
#untar um forma com margarina e colocar os ingedientes misturados
#ligar o forno 180 graus por 10 minutos
#colocar a vasilha no forno pré-aquecido
#esperar 45 minutos para assar (Verificar!!)
#retirar o bolo do forno, apenas se tiver pronto
#colocar o bolo na mesa para esfriar
#prepara a cobertura
#servir
#Fim

def fazer_bolo():
        # fermento =  1
        # ovos = 3
        # farinha = 3
        # chocolate = 2
        # leite = 1
        # margarina = 0.5
        # chantilly = 1
        # acucar = 3
        # sal = 0.05

    ingredientes = {
         "fermento":   1,
         "ovos": 3,
         "farinha":  3,
         "chocolate": 2,
         "leite": 1,
         "margarina":  0.5,
         "chantilly": 1,
         "acucar": 3,
         "sal": 0.05
    }

#modo de preparo
from time import sleep #inserir o sleep para dar um suspense
print('-'*50) #inseri para deixa mais intuitivo
print("Separe uma vasilha para misturar os ingredientes")
print("Acrescentar os ingredientes na vasilha")
print('-'*50) #inserir para deixar mais intuitivo
mistura_massa = ["fermento", "ovos", "farinha", "chocolate", "leite", "acucar","sal"]
print("Misturar os ingedientes na vasilha ate ficar homogeneo")
print("junte a forma e coloque os ingredientes")
print('-'*50) #inserir para deixar mais intuitivo
#temperatura = 180
# alterei o int para o float
temp = float(input("digite somente numeros para a temperatura do forno:"))
print('PROCESSANDO...')
sleep(3)#tempo
print('\n') #inserir para deixa mais intuitivo
temp_pre = float(input("entre com o tempo de pre-aquecimento somente com numeros:")) #alterei o int para float
print('PROCESSANDO...') #inserir para deixa mais intuitivo
sleep(3)#tempo
print('\n')#dar um espaço
print('-'*50)#mais intuitivo
print('aqueçendo o forno em {0}graus por {1}minutos'.format(temp, temp_pre))
print('-'*50)#intuitivo
sleep(4)#tempo

#inseri um novo if e else para melhorar o codigo
if temp >= 200:
  print('cuidado com essa temperatura ai ')

else:
  print('otima escolha de temperatura.')
  print('AGUARDE...')#intuitivo
sleep(4)#tempo

print('-'*50)#intuitivo
print('muito bem forno pré-aquecido so colocar vasilha no forno. ')
#tempo_preparo = 45
print('-'*50)
tempo_preparo = float(input("Digite o tempo de preparo em min lembrando que 1h equivale a 60 min:"))

#verificar se o bolo esta assado
print("Verificando se o bolo esta assado")
print('\n')
print('-'*50)
if tempo_preparo >= 45:
    print("Bolo Assado! Pode retirar do forno e colocar na mesa")

else:
    print("Bolo está cru, apressado! Espere")

print('-'*50)
print("Coloque a cobertura e só Servir!!")

#clear cpisa minha so pra lembra de como limpa