# -*- coding: utf-8 -*-
"""MUNDO ZUMBI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aLH0ytRbiSRIoDvxSE5dnnlqDnbttbK9
"""

from time import sleep
import random
# a tematica do jogo é baseada em um policial esta tendo um dia comum porem entra em confronto com bandidos e leva a pior
# ficando em coma durante 1 ano que dentro desse tempo surgir uma epidemia de um virus com mutações geneticas
# isso tudo ocorrendo no mundo e ele em um coma sem saber de nada .

print('''Você acorda em um hospital escuro e úmido.

 A única coisa que você consegue lembrar é que estava em um tiroteio contra bandidos que você estava perseguindo.

e que você e seu parceiro foi encuralado... , Você não entende aonde esta mas sabe que é uma sala de hospital :
''')

personagem = input('Qual é o seu nome ? ')
print(personagem)

print(f'"Olá {personagem}" - Você ouve gemidos e passos arrastados se aproximando, voçê pensa deve ser algum funcionario do hospital finalmente...')
print()
print()
print('...')
sleep(2)
print('......')
sleep(2)

print('E surge um zumbi bem na sua frente ,com o rosto todo em decomposição irreconhecivel com as tripas para fora querendo te devorar ')
print()
print('literalmente um choque algo nunca visto , oque você vai fazer?')
print('''
      [1] Fugir
      [2] Enfrentá-lo
''')

escolha = input('Escolha a opção [1] ou [2]: ')

if escolha == '1':
    print('Você decide fugir, procurando por uma saída. o zumbi se rasteja tentando seguir mais muito lento, você consegue escapar pela porta principal .')
    print('Você encontra-se ja fora do hospital , à sua frente tem tres coisas, ')
    print('qual delas você vai escolher?')
    print('''
          [3] bicicleta
          [4] um skate
          [5] e um carro
    ''')

    escolha_corredor = input('Escolha a opção [3], [4] ou [5]: ')

    if escolha_corredor == '3':
        print('Você caminha livremente com a bicicleta e reparando que não tinha presenca de uma alma viva e se pergunta algo esta errado.')
        print('Enquanto explora o local tem pequenos flashbacks do ocorrido .')
        print('sem prestar atenção pois ainda estava meio sonolento se depera com sua casa aonde encontra pistas que o ajuda para procurar sua familia.')
        print('Fim da história. Obrigado por jogar!')

    elif escolha_corredor == '4':
        print('Ao pegar o skate, você avista uma criança longe e decide ir até ela....')
        print('Você se aproxima e estranha o comportamento nada normal dessa criança de aproximadamente 5 a 6 anos ')
        print('Você lembra de que é a mais ou menos a idade do seu filho e fica curioso ao virar a garotinha ela te da uma mordida pois esta infequitada Obrigado por jogar!')

    elif escolha_corredor == '5':
        print('A terceira opção Você precisa fazer uma ligação direta para ligar o carro.')
        print('Enquanto faz isso tem pequenas lembranças antes do acidente, você descobre que tem uma familia e precisa achar eles ')
        print('tudo ok com o veiculo e o mais importante com combustivel ta na hora de achar sua familia nesse mundo zumbi. Fim da história. Obrigado por jogar!')

    else:
        print('Opção inválida. Por favor, escolha novamente.')

elif escolha == '2':
    print('Você decide enfrentar o zumbi. Ele estava com a os doocumentos no bolso e ao olha voçê descobre ser seu parceiro que estava no dia do confronto. .')
    print('Você decide enterrá lo nos fundos do hospital e logo após vai embora .')
    print('Enquanto exploram a cidade, vocês encontram evidências de que sua familia pode estar viva pois todas as fotos de familia havia sumido da sua casa.')
    print('então você decidem procurar por eles , eventualmente, depois de algumas semanas você encontra sua esposa e filho em um acampamento para sobreviventes.')
    print('Fim da história. Obrigado por jogar!')

else:
    print('Opção inválida. Por favor, escolha novamente.')