# -*- coding: utf-8 -*-
"""programas usando o ( math , random)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SN6j6JpgaKEb2sDOblhSeSHaW63cEwFs
"""

#para importa todas as funcionabilidade de um modulo(mais generalista )
import bebidas
# para importa apenas as funcionabilidade que eu escolher(um pouco mais especifico)
from doce import pudim

math #modulo(biblioteca)

ceil#aredondamento para cima
floor#aredondamento para baixo
trunc#ele vai eliminar um numero da virgula para frente sem fazer arendondamento
pow#potencia
sqrt#raiz quadrada
factorial#culculo fatoreal de um numero

#para toda a biblioteca
import math
#para apenas uma especifica
from math import sqrt
math.sqrt
math.ceil
math.trunc
math.pow
math.floor
math.factorial

import math
numero = int(input('digite um numero:'))
raiz = math.sqrt(numero)
print('a raiz de {} é igual a {}'.format(numero, math.ceil(raiz)))

import random
#random.random(para numeros aleatorios)
#num = random.randint(1,4) para numeros
#random.choice(escolher nomes aleatorio)

16
#crie um programa que leia um número real qualquer pelo teclado
# e montre na tela a sua porção inteira
# ex: digite um número:6.127
# o numero 6.127 tem a parte inteira 6

from math import trunc
#import math
num = float(input('escreva um numero:'))
#inteiro = math.trunc(num)
inteiro = trunc(num)
print('o numero {} tem a parte inteira {}'.format(num, trunc(inteiro)))
#print('o numero {} tem a parte inteira {}'.format(num, math.trunc(inteiro)))

num = float(input('digite um numero:'))
print('numero que você digitou foi {}, e a parte inteira dele é {}.'.format(num, int(num)))

17
#faça um programa que leia comprimento do cateto oposto e do cateto adjacente de um TRIANGULO RETANGULO,
#calcule e mostre o comprimento da hipotenusa.
import math
co = float(input('digite o numero do cateto oposto:'))
ca = float(input('digite o numero do cateto adjacente:'))
#co1 = math.pow(co,2)
#ca1 = math.pow(ca,2)
#soma = ca1 + co1
#raiz = math.sqrt(soma)
#pc = math.ceil(raiz)
hip = math.hypot(co, ca)
print('o comprimento da hipotenusa  de um triangulo retangulo é: {:.1f}'.format(hip))

co = float(input('digite o numero do cateto oposto'))
ca = float(input('digite o numero do cateto adjacente'))
hip = (co**2 + ca**2) ** (1/2)
print('o valor da hipotenusa de um triangulo retangulo é {:.1f}'.format(hip))

18
#faça um programa que leia um angulo qualquer e mostre na tela o valor do seno,cosseno e tangente
# desse angulo
#import math
from math import radians, sin, cos, tan
angulo = float(input('digite o seu angulo'))
#seno = math.sin(math.radians(angulo))
#cos = math.cos(math.radians(angulo))
#tang = math.tan(math.radians(angulo))
seno = sin(radians(angulo))
cos = cos(radians(angulo))
tang = tan(radians(angulo))
print('o angulo de {}\ntem o seno {:.2f}\ntem o cosseno {:.3f}\ne a sua tangente {:.3f} '.format(angulo, seno, cos, tang))

#um professor quer sortear um dos seu quatros alunos para apagar o quadro.
#faça um programa que ajude ele, lendo o nome deles e escrevendo o nome do escolhido.
import random
a = str(input('nome:'))
b = str(input('nome:'))
c = str(input('nome:'))
d = str(input('nome:'))
lista = [a, b, c, d]
print('o aluno sorteado foi {}'.format(random.choice(lista)))

20
# o mesmo professor do desafio anterior quer sortear a ordem de apresentação de trabalhos dos alunos.
#faça um programa que leia o nome dos quatro alunos e mostre a ordem sorteada

#import random
#(shuffle) serve para embaralhar uma lista e botar com uma ordem todos eles

from random import shuffle
a = str(input('primeiro aluno:'))
b = str(input('segundo aluno:'))
c = str(input('terceiro aluno:'))
d = str(input('quarto aluno:'))
lista = [a, b, c, d]
shuffle(lista)
#random.shuffle(lista)
print('os alunos sorteados sera')
print(lista)

21
#faça um programa em python que abra e reproduza o audio de um arquivo MP3
import pygame
pygame.get_init