# -*- coding: utf-8 -*-
"""progamas  aritmetico ( % * / )

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGlHvnd6buNcZbHDy0FIcwvT9coVmFx6
"""

#crie um programa que leia quanto dinheiro uma pessoa tem na carteira e mostre quantos dólares ela pode comprar
#considere us 1.00 = 4.98
real = float(input('quanto de dinheiro você tem na carteira: R$'))
dolar = real/4.98
print('com {}R$ voce pode compra {:.2f}US$'.format(real,dolar))

#faça um programa que leia a largura e altura de uma parede em metros ,
# calcule sua área e a quantidade de tinta necessária para pintá-la ,
# sabendo cada litro de tinta pinta uma área de 2 metros quadrados

b=float(input('digite a largura da parede em metros:M'))
a = float(input('digite a altura da parede em metros:M'))
#para medir uma area é so botar base x aultura
area = b * a
#a cada 2 metros quadrados usa 1 litro de tintas
print('sua área é {}m2 , então você usara {}litros de tintas'.format(area,(area/2)))

#faça um algoritmo que leia o preço de um produto e mostre seu novo preço , com 5% de *desconto*
produto = float(input('digite o valor do produto: R$'))
np = produto - (produto*5/100)
print(44*'-',end='')
print('>')
print('o preço que você inseriu foi {}R$.'.format(produto))
print(44*'-',end='')
print('>')
print('inserindo o desconto de 5% seu novo preço é {}R$.'.format(np))

#faça um algoritmo que leia o salário de um funcionário e mostre seu novo salário com 15% de aumento
salario = float(input('digite seu salario atual: R$'))
ns = salario + (salario*15/100)
print(40*'-',end='')
print('>')
print('seu novo salario é {}R$ com aumento de 15%'.format(ns))

produto = float(input('digite o valor do produto: R$'))
desc = produto - (produto*20/100)
aument = produto + (produto*35/100)
print(50*'-',end='')
print('>')
print('se o senhor(a) pagar em dinheiro tera um desconto e ira pagar {}R$'.format(desc))
print(50*'-',end='')
print('>')
print('se o senhor(a) para parcelado tera um reajuste de {}R$ '.format(aument))

#faça um codigo que converta digitando em graus converta para farenrait
g = float(input('informe a temperatura em graus:'))
f = 9*g / 5 + 32
print('a temperatura de {}graus corresponde a {}f!'.format(g, f))

#escreva um programa que pergunte a quantidade de km percorridos por um carro alugado
#e a quantidade de dias pelos quais ele foi alugado
#calcule o preço a pagar , sabendo que o carro custa R$60 POR DIA e R$0,15 POR KM rodado
km = float(input('quantos km foi percorrido com o carro:'))
dia = float(input('quantos dias ele foi alugado:'))
calculo = (dia*60)+ km*0.15
print('voçê informou rodou {}km e alugou durante{}dias então ira pagar {}r$'.format(km, dia, calculo))